### ISSUE TITLE
Discussion: Naming

### ISSUE THREAD

**Issue by jjl** [macchiato-framework/macchiato-futures#1]
Given that we're already operating under the `macchiato` top level namespace, maybe it would be nice to drop the `.core` ?

**Comment by jjl** [comment]
I'm currently implementing promises according to the clojure api (+ extras) on top of fibers, which has resulted in me starting to wrap fibers themselves, so we now implement not just futures, but fibers, promises and futures.

Is it perhaps time for a rename? I'm not sure that any of these pieces are big enough to warrant being put in their own libraries.

**Comment by yogthos** [comment]
I do think it would make sense to keep it all in one place.

**Comment by ricardojmendez** [comment]
Since we may add other approaches as well, how about renaming it to macchiato-sync?

**Comment by ricardojmendez** [comment]
Renamed. Closing.
